version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: fbrideradmin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: fbrider
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - fbrider-network

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - fbrider-network

volumes:
  postgres-data:
  mongo-data:

networks:
  fbrider-network:
    driver: bridge
