version: '3.8'

services:
  # Service for applying migrations
  db-migrations:
    build:
      context: .
      dockerfile: FbRider.Api/migrations.Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - postgres
    networks:
      - fb-rider-network
    entrypoint: ["/wait-for-it.sh", "postgres:5432", "--", "dotnet", "ef", "database", "update"]  # Wait for DB to be ready, then run migration

  # Main API service
  api:
    build:
      context: .
      dockerfile: FbRider.Api/Dockerfile
    ports:
      - "8080:8080" # Expose the API on host port 8080
      - "8081:8081" # Expose the HTTPS port
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/https.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1234
    volumes:
      - ./certs:/https:ro # Mount the certs folder as read-only
    depends_on:
      - postgres
      - db-migrations # Ensure migrations are done before API starts
    networks:
      - fb-rider-network

  # PostgreSQL service
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432" # Expose PostgreSQL on host port 5432
    environment:
      POSTGRES_DB: FbRiderDb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - fb-rider-network

networks:
  fb-rider-network:
    driver: bridge

volumes:
  postgres-data:
